version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy_proxy
    restart: always
    volumes:
      - ./Caddyfile.generated:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_net
    ports:
      - "80:80"
      - "443:443"

networks:
  caddy_net:
    external: true

volumes:
  caddy_data:
  caddy_config:
